services:
  roundcube:
    build: .
    container_name: roundcube_webmail
    ports:
      - "8080:80"
    volumes:
      - ./config:/var/www/html/config
      - ./logs:/var/www/html/logs
      - ./temp:/var/www/html/temp
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=mail
      - ROUNDCUBEMAIL_DEFAULT_PORT=143
      - ROUNDCUBEMAIL_SMTP_SERVER=mail
      - ROUNDCUBEMAIL_SMTP_PORT=25
      - ROUNDCUBEMAIL_DB_TYPE=mysql
      - ROUNDCUBEMAIL_DB_HOST=db
      - ROUNDCUBEMAIL_DB_NAME=roundcubemail
      - ROUNDCUBEMAIL_DB_USER=roundcube
      - ROUNDCUBEMAIL_DB_PASSWORD=roundcube_password
    depends_on:
      - db
      - mail
    restart: unless-stopped

  mail:
    image: mailserver/docker-mailserver:latest
    container_name: roundcube_mail
    hostname: mail.aa.aa
    domainname: aa.aa
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - mail_data:/var/mail
      - mail_state:/var/mail-state
      - mail_logs:/var/log/mail
      - ./mail-config/:/tmp/docker-mailserver/
    environment:
      - ENABLE_SPAMASSASSIN=0
      - ENABLE_CLAMAV=0
      - ENABLE_FAIL2BAN=0
      - ENABLE_POSTGREY=0
      - ONE_DIR=1
      - DMS_DEBUG=0
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: roundcube_db
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=roundcubemail
      - MYSQL_USER=roundcube
      - MYSQL_PASSWORD=roundcube_password
    volumes:
      - db_data:/var/lib/mysql
      - ./SQL/mysql.initial.sql:/docker-entrypoint-initdb.d/init.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped

volumes:
  db_data:
  mail_data:
  mail_state:
  mail_logs:
